/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "bank.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static int *
_inicializar_1 (void  *argp, struct svc_req *rqstp)
{
	return (inicializar_1_svc(rqstp));
}

static int *
_abre_1 (int  *argp, struct svc_req *rqstp)
{
	return (abre_1_svc(*argp, rqstp));
}

static int *
_fecha_1 (int  *argp, struct svc_req *rqstp)
{
	return (fecha_1_svc(*argp, rqstp));
}

static int *
_autentica_1 (int  *argp, struct svc_req *rqstp)
{
	return (autentica_1_svc(*argp, rqstp));
}

static float *
_saldo_1 (int  *argp, struct svc_req *rqstp)
{
	return (saldo_1_svc(*argp, rqstp));
}

static int *
_deposita_1 (deposita_1_argument *argp, struct svc_req *rqstp)
{
	return (deposita_1_svc(argp->arg1, argp->arg2, argp->arg3, rqstp));
}

static int *
_saca_1 (saca_1_argument *argp, struct svc_req *rqstp)
{
	return (saca_1_svc(argp->arg1, argp->arg2, argp->arg3, rqstp));
}

static int *
_assinatura_1 (void  *argp, struct svc_req *rqstp)
{
	return (assinatura_1_svc(rqstp));
}

static void
bankprog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		int abre_1_arg;
		int fecha_1_arg;
		int autentica_1_arg;
		int saldo_1_arg;
		deposita_1_argument deposita_1_arg;
		saca_1_argument saca_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case INICIALIZAR:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _inicializar_1;
		break;

	case ABRE:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _abre_1;
		break;

	case FECHA:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _fecha_1;
		break;

	case AUTENTICA:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _autentica_1;
		break;

	case SALDO:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) _saldo_1;
		break;

	case DEPOSITA:
		_xdr_argument = (xdrproc_t) xdr_deposita_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _deposita_1;
		break;

	case SACA:
		_xdr_argument = (xdrproc_t) xdr_saca_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _saca_1;
		break;

	case ASSINATURA:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _assinatura_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (BANKPROG, BANKVERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, BANKPROG, BANKVERS, bankprog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (BANKPROG, BANKVERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, BANKPROG, BANKVERS, bankprog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (BANKPROG, BANKVERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
