/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _BANK_H_RPCGEN
#define _BANK_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct conta {
	int id;
	float saldo;
};
typedef struct conta conta;

struct deposita_1_argument {
	int arg1;
	float arg2;
};
typedef struct deposita_1_argument deposita_1_argument;

struct saca_1_argument {
	int arg1;
	int arg2;
};
typedef struct saca_1_argument saca_1_argument;

#define BANKPROG 0x30090949
#define BANKVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define INICIALIZAR 1
extern  int * inicializar_1(CLIENT *);
extern  int * inicializar_1_svc(struct svc_req *);
#define ABRE 2
extern  int * abre_1(CLIENT *);
extern  int * abre_1_svc(struct svc_req *);
#define FECHA 3
extern  int * fecha_1(int , CLIENT *);
extern  int * fecha_1_svc(int , struct svc_req *);
#define AUTENTICA 4
extern  int * autentica_1(int , CLIENT *);
extern  int * autentica_1_svc(int , struct svc_req *);
#define SALDO 5
extern  float * saldo_1(int , CLIENT *);
extern  float * saldo_1_svc(int , struct svc_req *);
#define DEPOSITA 6
extern  int * deposita_1(int , float , CLIENT *);
extern  int * deposita_1_svc(int , float , struct svc_req *);
#define SACA 7
extern  int * saca_1(int , int , CLIENT *);
extern  int * saca_1_svc(int , int , struct svc_req *);
#define ASSINATURA 8
extern  int * assinatura_1(CLIENT *);
extern  int * assinatura_1_svc(struct svc_req *);
extern int bankprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define INICIALIZAR 1
extern  int * inicializar_1();
extern  int * inicializar_1_svc();
#define ABRE 2
extern  int * abre_1();
extern  int * abre_1_svc();
#define FECHA 3
extern  int * fecha_1();
extern  int * fecha_1_svc();
#define AUTENTICA 4
extern  int * autentica_1();
extern  int * autentica_1_svc();
#define SALDO 5
extern  float * saldo_1();
extern  float * saldo_1_svc();
#define DEPOSITA 6
extern  int * deposita_1();
extern  int * deposita_1_svc();
#define SACA 7
extern  int * saca_1();
extern  int * saca_1_svc();
#define ASSINATURA 8
extern  int * assinatura_1();
extern  int * assinatura_1_svc();
extern int bankprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_conta (XDR *, conta*);
extern  bool_t xdr_deposita_1_argument (XDR *, deposita_1_argument*);
extern  bool_t xdr_saca_1_argument (XDR *, saca_1_argument*);

#else /* K&R C */
extern bool_t xdr_conta ();
extern bool_t xdr_deposita_1_argument ();
extern bool_t xdr_saca_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_BANK_H_RPCGEN */
